variables:
  AWS_ACCESS_KEY_ID: $TF_VAR_access_key
  AWS_SECRET_ACCESS_KEY: $TF_VAR_access_key
  HTTPS_PROXY: http://proxy.csoc.thales:328/

image:
  name: hashicorp/terraform:light
  entrypoint: [""]

before_script:
  - terraform init

cache:
  key: "${TF_ROOT}"
  paths:
    - ${TF_ROOT}/.terraform/

fmt:
  stage: build
  script:
  - terraform fmt
  allow_failure: true
  rules:
  - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  - if: "$CI_OPEN_MERGE_REQUESTS"
    when: never

validate:
  stage: build
  tags:
    - docker
  script:
  - terraform validate
  rules:
  - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  - if: "$CI_OPEN_MERGE_REQUESTS"
    when: never
  - if: "$CI_COMMIT_BRANCH"

build:
  stage: build
  tags:
    - docker
  script:
    - terraform plan
    - terraform plan-json
  rules:
  - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  - if: "$CI_OPEN_MERGE_REQUESTS"
    when: never
  - if: "$CI_COMMIT_BRANCH"

deploy:
  stage: deploy
  tags:
    - docker
  script:
    - terraform import -auto-approve