variables:
  AWS_ACCESS_KEY_ID: $TF_VAR_access_key
  AWS_SECRET_ACCESS_KEY: $TF_VAR_access_key
  HTTPS_PROXY: http://proxy.csoc.thales:328/

include:
  - template: Terraform.latest.gitlab-ci.yml

cache:
  key: "${TF_ROOT}"
  paths:
    - ${TF_ROOT}/.terraform/

fmt:
  extends: .terraform:fmt

validate:
  extends: .terraform:validate

build:
  extends: .terraform:build

deploy:
  script:
    - "echo toto"