variables:
  AWS_ACCESS_KEY_ID: $TF_VAR_access_key
  AWS_SECRET_ACCESS_KEY: $TF_VAR_access_key
  HTTPS_PROXY: http://proxy.csoc.thales:328/

include:
  - template: Terraform.latest.gitlab-ci.yml

cache:
  key: "${TF_ROOT}"
  paths:
    - ${TF_ROOT}/.terraform/

fmt:
  stage: validate
  image: hashicorp/terraform:light
  script:
  - fmt
  allow_failure: true
  rules:
  - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  - if: "$CI_OPEN_MERGE_REQUESTS"
    when: never

validate:
  stage: validate
  image: hashicorp/terraform:light
  tags:
    - docker
  extends: .terraform:validate
  script:
  - validate
  rules:
  - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  - if: "$CI_OPEN_MERGE_REQUESTS"
    when: never
  - if: "$CI_COMMIT_BRANCH"

build:
  stage: build
  image: hashicorp/terraform:light
  tags:
    - docker
  extends: .terraform:build
  script:
    - terraform plan
    - terraform plan-json
  rules:
  - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  - if: "$CI_OPEN_MERGE_REQUESTS"
    when: never
  - if: "$CI_COMMIT_BRANCH"

deploy:
  stage: deploy
  image: hashicorp/terraform:light
  tags:
    - docker
  script:
    - terraform init
    - terraform import -auto-approve