variables:
  AWS_ACCESS_KEY_ID: $TF_VAR_access_key
  AWS_SECRET_ACCESS_KEY: $TF_VAR_access_key
  HTTPS_PROXY: http://proxy.csoc.thales:328/

image:
  name: hashicorp/terraform:light

include:
  - template: Terraform.latest.gitlab-ci.yml

cache:
  key: "${TF_ROOT}"
  paths:
    - ${TF_ROOT}/.terraform/

fmt:
  extends: .terraform:fmt

validate:
  image: hashicorp/terraform:light
  extends: .terraform:validate
  script:
  - cd "${TF_ROOT}"
  - terraform validate

build:
  image: hashicorp/terraform:light
  extends: .terraform:build
  script:
    - cd "${TF_ROOT}"
    - terraform plan
    - terraform plan-json

deploy:
  image: hashicorp/terraform:light
  script:
    - terraform init
    - terraform import -auto-approve